### PR TITLE
fix: provide envelope for http rules

### LINKED ISSUE #166: HTTP Rule Enveloping
Passing "enveloped" to a standard webhook/HTTP rule has no effect, which means these rules cannot be created when the source is `channel.lifecycle` or `channel.occupancy` as realtime requires enveloping for these source types.

### PR DESCRIPTION
**Pull request by AndyTWF**
Previously, passing "enveloped" to a rule target, when that rule was a standard webhook/HTTP rule it would be ignored.

Now, the provider properly applies "enveloped" to the rule when the `request_mode` is "single".

Fixes #166

### CODE REVIEW

File: internal/provider/resource_ably_rule_http.go [hunk 1]
```diff
@@ -28,7 +28,8 @@ func (r resourceRuleHTTP) GetSchema(_ context.Context) (tfsdk.Schema, diag.Diagn
 				Optional:    true,
 				Description: "The signing key ID for use in batch mode. Ably will optionally sign the payload using an API key ensuring your servers can validate the payload using the private API key. See the [webhook security docs](https://ably.com/docs/general/webhooks#security) for more information",
 			},
-			"format": GetFormatSchema(),
+			"format":    GetFormatSchema(),
+			"enveloped": GetEnvelopedchema(),
```
Comment (lmars) [inline internal/provider/resource_ably_rule_http.go:32]: Should this be `GetEnvelopedSchema()`?

File: internal/provider/resource_ably_rule_http_test.go [hunk 2]
```diff
@@ -65,13 +67,15 @@ func TestAccAblyRuleHTTP(t *testing.T) {
 					"ably_api_key.api_key_1.id",
 					"https://example1.com/webhooks",
 					"msgpack",
+					"",
```
Comment (lmars) [inline internal/provider/resource_ably_rule_http_test.go:70]: I haven't worked on this provider before, but just looking at the surrounding code, it seems like this should be a true/false value, rather than a string which is either `enveloped = true` or an empty string?

File: internal/provider/resource_ably_rule_http.go (hunk 1 above)
Comment (AndyTWF) [reply internal/provider/resource_ably_rule_http.go:32]: It's a typo throughout the codebase :D But I'll fix it now!

File: internal/provider/resource_ably_rule_http_test.go (hunk 2 above)
Comment (AndyTWF) [reply internal/provider/resource_ably_rule_http_test.go]: https://github.com/ably/terraform-provider-ably/pull/167/commits/147d471ad0e97b8b73aac9f5b0111943808ffea9

File: internal/provider/resource_ably_rule_http.go (hunk 1 above)
Comment (AndyTWF) [reply internal/provider/resource_ably_rule_http.go]: https://github.com/ably/terraform-provider-ably/pull/167/commits/90f4cf033bad2e627a5fb9ab5cb5130ae1e2765b

Comment (lmars) [reply internal/provider/resource_ably_rule_http.go]: 👍

**Review by lmars — APPROVED** [review]
LGTM, although I defer to @graham-russell who is much more familiar with this.

File: internal/provider/resource_ably_rule_http_test.go (hunk 2 above)
Comment (lmars) [reply internal/provider/resource_ably_rule_http_test.go]: 👍

**Review by graham-russell — APPROVED** [review]
LGTM!
